#!/usr/bin/env bash

# DEPENDENCIES

# ffmpeg to record mp4 video and convert to webm
# slop to get coordinates where to record, https://github.com/naelstrof/slop
# sox to play audio file


type slop ffmpeg play > /dev/null || exit

delay=3
path="$HOME/Pictures/vid_$(date +"%s")"

beep() {
    play shutter.ogg
}


# deal with passed arguments
if [ $# -gt 1 ]; then
    dur="$1"
    path=$2
elif [ $# -gt 0 ]; then
    dur="$1"
else
    dur="10"
fi

# get $X $Y $W $H variables from slop
eval $(slop)

# show countdown
for (( i=$delay; i>0; --i )) ; do
    echo $i
    sleep 1
done

beep
# record mp4
ffmpeg -video_size $W\x$H -framerate 25 -f x11grab -i :0+$X,$Y -t $dur $path.mp4
beep


