# Here we define labels for fields
LBL = {'id': 'αα',
       'afm': 'ΑΦΜ',
       'epon': 'Επώνυμο',
       'addr': 'Διεύθυνση',
       'rdat': 'Ημερομηνία',
       'doy': 'ΔΟΥ',
       'poli': 'Πόλη',
       'dekd': 'Δοκιμή',
       'sygp': 'Ναι/όχι',
       'per': 'Περιγραφή',
       'val': 'Τιμή',
       'odos': 'Οδός',
       'bon': 'Δοκιμαστικό',
       }