# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\prj\pyQtAccounting\main.ui'
#
# Created: Fri Feb 03 14:58:58 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 140)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/euro")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.bOpenIsozygio = QtGui.QPushButton(self.centralwidget)
        self.bOpenIsozygio.setGeometry(QtCore.QRect(10, 0, 51, 51))
        self.bOpenIsozygio.setAutoFillBackground(False)
        self.bOpenIsozygio.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/balance")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bOpenIsozygio.setIcon(icon1)
        self.bOpenIsozygio.setIconSize(QtCore.QSize(30, 30))
        self.bOpenIsozygio.setDefault(False)
        self.bOpenIsozygio.setFlat(False)
        self.bOpenIsozygio.setObjectName(_fromUtf8("bOpenIsozygio"))
        self.bInsertTransaction = QtGui.QPushButton(self.centralwidget)
        self.bInsertTransaction.setGeometry(QtCore.QRect(70, 0, 51, 51))
        self.bInsertTransaction.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/add")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bInsertTransaction.setIcon(icon2)
        self.bInsertTransaction.setIconSize(QtCore.QSize(30, 30))
        self.bInsertTransaction.setFlat(False)
        self.bInsertTransaction.setObjectName(_fromUtf8("bInsertTransaction"))
        self.bifsprint = QtGui.QPushButton(self.centralwidget)
        self.bifsprint.setGeometry(QtCore.QRect(130, 0, 51, 51))
        self.bifsprint.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/print")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bifsprint.setIcon(icon3)
        self.bifsprint.setIconSize(QtCore.QSize(30, 30))
        self.bifsprint.setAutoDefault(False)
        self.bifsprint.setDefault(False)
        self.bifsprint.setFlat(False)
        self.bifsprint.setObjectName(_fromUtf8("bifsprint"))
        self.bOpenImerologio = QtGui.QPushButton(self.centralwidget)
        self.bOpenImerologio.setGeometry(QtCore.QRect(190, 0, 93, 51))
        self.bOpenImerologio.setObjectName(_fromUtf8("bOpenImerologio"))
        self.btree = QtGui.QPushButton(self.centralwidget)
        self.btree.setGeometry(QtCore.QRect(360, 0, 93, 51))
        self.btree.setObjectName(_fromUtf8("btree"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_new = QtGui.QAction(MainWindow)
        self.action_new.setObjectName(_fromUtf8("action_new"))
        self.action_open = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/fileopen")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_open.setIcon(icon4)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.action_exit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/filequit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_exit.setIcon(icon5)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_isozygio = QtGui.QAction(MainWindow)
        self.action_isozygio.setIcon(icon1)
        self.action_isozygio.setObjectName(_fromUtf8("action_isozygio"))
        self.action_eggrafi = QtGui.QAction(MainWindow)
        self.action_eggrafi.setIcon(icon2)
        self.action_eggrafi.setObjectName(_fromUtf8("action_eggrafi"))
        self.action_ifsPrint = QtGui.QAction(MainWindow)
        self.action_ifsPrint.setObjectName(_fromUtf8("action_ifsPrint"))
        self.menu.addAction(self.action_new)
        self.menu.addAction(self.action_open)
        self.menu.addAction(self.action_exit)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_isozygio)
        self.menu_2.addAction(self.action_eggrafi)
        self.menu_3.addAction(self.action_ifsPrint)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Λογιστική 2012", None, QtGui.QApplication.UnicodeUTF8))
        self.bOpenIsozygio.setToolTip(QtGui.QApplication.translate("MainWindow", "Ισοζύγιο Λογαριασμών", None, QtGui.QApplication.UnicodeUTF8))
        self.bInsertTransaction.setToolTip(QtGui.QApplication.translate("MainWindow", "Προσθήκη Νέας Εγγραφής", None, QtGui.QApplication.UnicodeUTF8))
        self.bifsprint.setToolTip(QtGui.QApplication.translate("MainWindow", "Εκτύπωση Ημερήσιου Φύλλου Συναλλαγών", None, QtGui.QApplication.UnicodeUTF8))
        self.bOpenImerologio.setText(QtGui.QApplication.translate("MainWindow", "Ημερολόγιο", None, QtGui.QApplication.UnicodeUTF8))
        self.btree.setText(QtGui.QApplication.translate("MainWindow", "tree", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Αρχείο", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Λογιστική", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Εκτυπώσεις", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setText(QtGui.QApplication.translate("MainWindow", "Νέο", None, QtGui.QApplication.UnicodeUTF8))
        self.action_new.setToolTip(QtGui.QApplication.translate("MainWindow", "Δημιουργία Νέας Βάσης Δεδομένων", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "Άνοιγμα", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setToolTip(QtGui.QApplication.translate("MainWindow", "Άνοιγμα υπάρχουσας Βάσης Δεδομένων", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "Έξοδος", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setToolTip(QtGui.QApplication.translate("MainWindow", "Έξοδος από την εφαρμογή", None, QtGui.QApplication.UnicodeUTF8))
        self.action_isozygio.setText(QtGui.QApplication.translate("MainWindow", "Ισοζύγιο", None, QtGui.QApplication.UnicodeUTF8))
        self.action_eggrafi.setText(QtGui.QApplication.translate("MainWindow", "Νέα εγγραφή", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ifsPrint.setText(QtGui.QApplication.translate("MainWindow", "Ημερήσιο Φύλλο Συναλλαγών", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
