# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\ted\Dropbox\prj\m13\gui\erg.ui'
#
# Created: Fri Feb 15 17:09:22 2013
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(269, 423)
        self.t_epon = QtGui.QLineEdit(Dialog)
        self.t_epon.setGeometry(QtCore.QRect(107, 16, 133, 20))
        self.t_epon.setReadOnly(True)
        self.t_epon.setObjectName(_fromUtf8("t_epon"))
        self.lbEponymo = QtGui.QLabel(Dialog)
        self.lbEponymo.setGeometry(QtCore.QRect(11, 16, 44, 16))
        self.lbEponymo.setObjectName(_fromUtf8("lbEponymo"))
        self.t_onom = QtGui.QLineEdit(Dialog)
        self.t_onom.setGeometry(QtCore.QRect(107, 42, 133, 20))
        self.t_onom.setReadOnly(True)
        self.t_onom.setObjectName(_fromUtf8("t_onom"))
        self.lbEponymo_2 = QtGui.QLabel(Dialog)
        self.lbEponymo_2.setGeometry(QtCore.QRect(11, 42, 33, 16))
        self.lbEponymo_2.setObjectName(_fromUtf8("lbEponymo_2"))
        self.t_pat = QtGui.QLineEdit(Dialog)
        self.t_pat.setGeometry(QtCore.QRect(107, 68, 133, 20))
        self.t_pat.setText(_fromUtf8(""))
        self.t_pat.setReadOnly(True)
        self.t_pat.setObjectName(_fromUtf8("t_pat"))
        self.lbEponymo_3 = QtGui.QLabel(Dialog)
        self.lbEponymo_3.setGeometry(QtCore.QRect(11, 68, 71, 16))
        self.lbEponymo_3.setObjectName(_fromUtf8("lbEponymo_3"))
        self.t_mit = QtGui.QLineEdit(Dialog)
        self.t_mit.setGeometry(QtCore.QRect(107, 94, 133, 20))
        self.t_mit.setText(_fromUtf8(""))
        self.t_mit.setReadOnly(True)
        self.t_mit.setObjectName(_fromUtf8("t_mit"))
        self.lbEponymo_4 = QtGui.QLabel(Dialog)
        self.lbEponymo_4.setGeometry(QtCore.QRect(11, 94, 77, 16))
        self.lbEponymo_4.setObjectName(_fromUtf8("lbEponymo_4"))
        self.d_gen = QtGui.QDateEdit(Dialog)
        self.d_gen.setGeometry(QtCore.QRect(107, 172, 83, 20))
        self.d_gen.setReadOnly(True)
        self.d_gen.setCalendarPopup(True)
        self.d_gen.setObjectName(_fromUtf8("d_gen"))
        self.lbEponymo_5 = QtGui.QLabel(Dialog)
        self.lbEponymo_5.setGeometry(QtCore.QRect(11, 172, 80, 16))
        self.lbEponymo_5.setObjectName(_fromUtf8("lbEponymo_5"))
        self.lbEponymo_6 = QtGui.QLabel(Dialog)
        self.lbEponymo_6.setGeometry(QtCore.QRect(11, 276, 90, 16))
        self.lbEponymo_6.setObjectName(_fromUtf8("lbEponymo_6"))
        self.d_pros = QtGui.QDateEdit(Dialog)
        self.d_pros.setGeometry(QtCore.QRect(107, 276, 83, 20))
        self.d_pros.setReadOnly(True)
        self.d_pros.setCalendarPopup(True)
        self.d_pros.setObjectName(_fromUtf8("d_pros"))
        self.lbEponymo_7 = QtGui.QLabel(Dialog)
        self.lbEponymo_7.setGeometry(QtCore.QRect(11, 224, 44, 16))
        self.lbEponymo_7.setObjectName(_fromUtf8("lbEponymo_7"))
        self.t_amka = QtGui.QLineEdit(Dialog)
        self.t_amka.setGeometry(QtCore.QRect(107, 224, 101, 20))
        self.t_amka.setText(_fromUtf8(""))
        self.t_amka.setReadOnly(True)
        self.t_amka.setObjectName(_fromUtf8("t_amka"))
        self.lbEponymo_8 = QtGui.QLabel(Dialog)
        self.lbEponymo_8.setGeometry(QtCore.QRect(11, 198, 35, 16))
        self.lbEponymo_8.setObjectName(_fromUtf8("lbEponymo_8"))
        self.t_afm = QtGui.QLineEdit(Dialog)
        self.t_afm.setGeometry(QtCore.QRect(107, 198, 91, 20))
        self.t_afm.setText(_fromUtf8(""))
        self.t_afm.setReadOnly(True)
        self.t_afm.setObjectName(_fromUtf8("t_afm"))
        self.t_amika = QtGui.QLineEdit(Dialog)
        self.t_amika.setGeometry(QtCore.QRect(107, 250, 71, 20))
        self.t_amika.setText(_fromUtf8(""))
        self.t_amika.setReadOnly(True)
        self.t_amika.setObjectName(_fromUtf8("t_amika"))
        self.lbEponymo_9 = QtGui.QLabel(Dialog)
        self.lbEponymo_9.setGeometry(QtCore.QRect(11, 250, 34, 16))
        self.lbEponymo_9.setObjectName(_fromUtf8("lbEponymo_9"))
        self.lbEponymo_10 = QtGui.QLabel(Dialog)
        self.lbEponymo_10.setGeometry(QtCore.QRect(11, 120, 26, 16))
        self.lbEponymo_10.setObjectName(_fromUtf8("lbEponymo_10"))
        self.lbEponymo_11 = QtGui.QLabel(Dialog)
        self.lbEponymo_11.setGeometry(QtCore.QRect(11, 146, 84, 16))
        self.lbEponymo_11.setObjectName(_fromUtf8("lbEponymo_11"))
        self.lbEponymo_12 = QtGui.QLabel(Dialog)
        self.lbEponymo_12.setGeometry(QtCore.QRect(11, 302, 62, 16))
        self.lbEponymo_12.setObjectName(_fromUtf8("lbEponymo_12"))
        self.t_proy = QtGui.QLineEdit(Dialog)
        self.t_proy.setGeometry(QtCore.QRect(107, 302, 51, 20))
        self.t_proy.setText(_fromUtf8(""))
        self.t_proy.setReadOnly(True)
        self.t_proy.setObjectName(_fromUtf8("t_proy"))
        self.t_papod = QtGui.QLineEdit(Dialog)
        self.t_papod.setGeometry(QtCore.QRect(107, 354, 71, 20))
        self.t_papod.setText(_fromUtf8(""))
        self.t_papod.setReadOnly(True)
        self.t_papod.setObjectName(_fromUtf8("t_papod"))
        self.lbEponymo_13 = QtGui.QLabel(Dialog)
        self.lbEponymo_13.setGeometry(QtCore.QRect(11, 354, 47, 16))
        self.lbEponymo_13.setObjectName(_fromUtf8("lbEponymo_13"))
        self.lbEponymo_14 = QtGui.QLabel(Dialog)
        self.lbEponymo_14.setGeometry(QtCore.QRect(11, 328, 29, 16))
        self.lbEponymo_14.setObjectName(_fromUtf8("lbEponymo_14"))
        self.t_sex = QtGui.QLineEdit(Dialog)
        self.t_sex.setGeometry(QtCore.QRect(107, 120, 71, 20))
        self.t_sex.setReadOnly(True)
        self.t_sex.setObjectName(_fromUtf8("t_sex"))
        self.t_cat = QtGui.QLineEdit(Dialog)
        self.t_cat.setGeometry(QtCore.QRect(107, 146, 131, 20))
        self.t_cat.setReadOnly(True)
        self.t_cat.setObjectName(_fromUtf8("t_cat"))
        self.t_mis = QtGui.QLineEdit(Dialog)
        self.t_mis.setGeometry(QtCore.QRect(107, 328, 81, 20))
        self.t_mis.setReadOnly(True)
        self.t_mis.setObjectName(_fromUtf8("t_mis"))
        self.lbEponymo.setBuddy(self.t_epon)
        self.lbEponymo_2.setBuddy(self.t_onom)
        self.lbEponymo_3.setBuddy(self.t_pat)
        self.lbEponymo_4.setBuddy(self.t_mit)
        self.lbEponymo_5.setBuddy(self.d_gen)
        self.lbEponymo_6.setBuddy(self.d_pros)
        self.lbEponymo_7.setBuddy(self.t_amka)
        self.lbEponymo_8.setBuddy(self.t_afm)
        self.lbEponymo_9.setBuddy(self.t_amika)
        self.lbEponymo_10.setBuddy(self.t_sex)
        self.lbEponymo_11.setBuddy(self.t_cat)
        self.lbEponymo_12.setBuddy(self.t_proy)
        self.lbEponymo_13.setBuddy(self.t_papod)
        self.lbEponymo_14.setBuddy(self.t_mis)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.t_epon, self.t_onom)
        Dialog.setTabOrder(self.t_onom, self.t_pat)
        Dialog.setTabOrder(self.t_pat, self.t_mit)
        Dialog.setTabOrder(self.t_mit, self.d_gen)
        Dialog.setTabOrder(self.d_gen, self.t_afm)
        Dialog.setTabOrder(self.t_afm, self.t_amka)
        Dialog.setTabOrder(self.t_amka, self.t_amika)
        Dialog.setTabOrder(self.t_amika, self.d_pros)
        Dialog.setTabOrder(self.d_pros, self.t_proy)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Στοιχεία εργαζομένων", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo.setText(QtGui.QApplication.translate("Dialog", "Επώνυμο", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_2.setText(QtGui.QApplication.translate("Dialog", "Όνομα", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_3.setText(QtGui.QApplication.translate("Dialog", "Όνομα Πατέρα", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_4.setText(QtGui.QApplication.translate("Dialog", "Όνομα Μητέρας", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_5.setText(QtGui.QApplication.translate("Dialog", "Ημ/νία Γέννησης", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_6.setText(QtGui.QApplication.translate("Dialog", "Ημ/νία Πρόσληψης", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_7.setText(QtGui.QApplication.translate("Dialog", "Α.Μ.Κ.Α.", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_8.setText(QtGui.QApplication.translate("Dialog", "Α.Φ.Μ.", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_9.setText(QtGui.QApplication.translate("Dialog", "Αμ.ΙΚΑ", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_10.setText(QtGui.QApplication.translate("Dialog", "Φύλο", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_11.setText(QtGui.QApplication.translate("Dialog", "Οικογ.Κατάσταση", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_12.setText(QtGui.QApplication.translate("Dialog", "Προυπηρεσία", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_13.setText(QtGui.QApplication.translate("Dialog", "Αποδοχές", None, QtGui.QApplication.UnicodeUTF8))
        self.lbEponymo_14.setText(QtGui.QApplication.translate("Dialog", "Τύπος", None, QtGui.QApplication.UnicodeUTF8))

