# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Dropbox\prj\m13\gui\main.ui'
#
# Created: Sat May 16 16:58:52 2015
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/m13")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.treeMis = QtGui.QTreeView(self.centralwidget)
        self.treeMis.setObjectName(_fromUtf8("treeMis"))
        self.verticalLayout.addWidget(self.treeMis)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_5 = QtGui.QMenu(self.menu_2)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        self.menu_4 = QtGui.QMenu(self.menu_3)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_6 = QtGui.QMenu(self.menubar)
        self.menu_6.setObjectName(_fromUtf8("menu_6"))
        self.menuAdministration = QtGui.QMenu(self.menubar)
        self.menuAdministration.setObjectName(_fromUtf8("menuAdministration"))
        self.menu_7 = QtGui.QMenu(self.menubar)
        self.menu_7.setObjectName(_fromUtf8("menu_7"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.a_open = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/fileOpen")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_open.setIcon(icon1)
        self.a_open.setObjectName(_fromUtf8("a_open"))
        self.a_new = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/fileNew")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_new.setIcon(icon2)
        self.a_new.setObjectName(_fromUtf8("a_new"))
        self.a_print_report = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/print")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_print_report.setIcon(icon3)
        self.a_print_report.setObjectName(_fromUtf8("a_print_report"))
        self.a_pros = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/newProsopo")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_pros.setIcon(icon4)
        self.a_pros.setObjectName(_fromUtf8("a_pros"))
        self.a_apol = QtGui.QAction(MainWindow)
        self.a_apol.setObjectName(_fromUtf8("a_apol"))
        self.a_apox = QtGui.QAction(MainWindow)
        self.a_apox.setObjectName(_fromUtf8("a_apox"))
        self.a_fmyFiscal = QtGui.QAction(MainWindow)
        self.a_fmyFiscal.setObjectName(_fromUtf8("a_fmyFiscal"))
        self.a_apd = QtGui.QAction(MainWindow)
        self.a_apd.setObjectName(_fromUtf8("a_apd"))
        self.a_calcmis = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/add")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_calcmis.setIcon(icon5)
        self.a_calcmis.setObjectName(_fromUtf8("a_calcmis"))
        self.a_tables = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/table")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_tables.setIcon(icon6)
        self.a_tables.setObjectName(_fromUtf8("a_tables"))
        self.a_fpr = QtGui.QAction(MainWindow)
        self.a_fpr.setIcon(icon4)
        self.a_fpr.setObjectName(_fromUtf8("a_fpr"))
        self.a_pard = QtGui.QAction(MainWindow)
        self.a_pard.setObjectName(_fromUtf8("a_pard"))
        self.a_exit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/exit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_exit.setIcon(icon7)
        self.a_exit.setObjectName(_fromUtf8("a_exit"))
        self.a_peri = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/info")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_peri.setIcon(icon8)
        self.a_peri.setObjectName(_fromUtf8("a_peri"))
        self.a_sql = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/pr/sql")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.a_sql.setIcon(icon9)
        self.a_sql.setObjectName(_fromUtf8("a_sql"))
        self.a_par = QtGui.QAction(MainWindow)
        self.a_par.setObjectName(_fromUtf8("a_par"))
        self.a_xrisi = QtGui.QAction(MainWindow)
        self.a_xrisi.setObjectName(_fromUtf8("a_xrisi"))
        self.a_eid = QtGui.QAction(MainWindow)
        self.a_eid.setObjectName(_fromUtf8("a_eid"))
        self.a_ypok = QtGui.QAction(MainWindow)
        self.a_ypok.setObjectName(_fromUtf8("a_ypok"))
        self.a_auto_par = QtGui.QAction(MainWindow)
        self.a_auto_par.setObjectName(_fromUtf8("a_auto_par"))
        self.a_pros_wizard = QtGui.QAction(MainWindow)
        self.a_pros_wizard.setObjectName(_fromUtf8("a_pros_wizard"))
        self.a_print_report_apod = QtGui.QAction(MainWindow)
        self.a_print_report_apod.setIcon(icon3)
        self.a_print_report_apod.setObjectName(_fromUtf8("a_print_report_apod"))
        self.menu.addAction(self.a_open)
        self.menu.addAction(self.a_new)
        self.menu.addSeparator()
        self.menu.addAction(self.a_exit)
        self.menu_5.addAction(self.a_fmyFiscal)
        self.menu_5.addAction(self.a_apd)
        self.menu_2.addAction(self.a_print_report)
        self.menu_2.addAction(self.a_print_report_apod)
        self.menu_2.addAction(self.menu_5.menuAction())
        self.menu_4.addSeparator()
        self.menu_4.addAction(self.a_apol)
        self.menu_4.addAction(self.a_apox)
        self.menu_3.addAction(self.a_fpr)
        self.menu_3.addAction(self.a_pros)
        self.menu_3.addAction(self.a_pros_wizard)
        self.menu_3.addAction(self.menu_4.menuAction())
        self.menu_6.addAction(self.a_auto_par)
        self.menu_6.addAction(self.a_par)
        self.menu_6.addAction(self.a_pard)
        self.menu_6.addAction(self.a_calcmis)
        self.menuAdministration.addAction(self.a_tables)
        self.menuAdministration.addAction(self.a_sql)
        self.menuAdministration.addAction(self.a_xrisi)
        self.menuAdministration.addAction(self.a_eid)
        self.menuAdministration.addAction(self.a_ypok)
        self.menu_7.addAction(self.a_peri)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())
        self.menubar.addAction(self.menuAdministration.menuAction())
        self.menubar.addAction(self.menu_7.menuAction())
        self.toolBar.addAction(self.a_open)
        self.toolBar.addAction(self.a_new)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.a_print_report)
        self.toolBar.addAction(self.a_pros)
        self.toolBar.addAction(self.a_tables)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "Δοκιμή1", None))
        self.menu.setTitle(_translate("MainWindow", "Αρχείο", None))
        self.menu_2.setTitle(_translate("MainWindow", "Εκτυπώσεις", None))
        self.menu_5.setTitle(_translate("MainWindow", "Δημιουργία Αρχείων", None))
        self.menu_3.setTitle(_translate("MainWindow", "Εργαζόμενοι", None))
        self.menu_4.setTitle(_translate("MainWindow", "Αποχωρήσεις", None))
        self.menu_6.setTitle(_translate("MainWindow", "Υπολογισμοί", None))
        self.menuAdministration.setTitle(_translate("MainWindow", "Παράμετροι", None))
        self.menu_7.setTitle(_translate("MainWindow", "Βοήθεια", None))
        self.statusbar.setToolTip(_translate("MainWindow", "Κατάσταση", None))
        self.statusbar.setStatusTip(_translate("MainWindow", "Όλα καλά", None))
        self.statusbar.setWhatsThis(_translate("MainWindow", "Εδώ βλέπουμε την κατάσταση της εφαρμογής", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.a_open.setText(_translate("MainWindow", "Άνοιγμα", None))
        self.a_open.setStatusTip(_translate("MainWindow", "Άνοιμα Αρχείου εταιρίας", None))
        self.a_new.setText(_translate("MainWindow", "Νέο", None))
        self.a_new.setToolTip(_translate("MainWindow", "Νέο Αρχείο εταιρίας", None))
        self.a_new.setStatusTip(_translate("MainWindow", "Δημιουργία Νέου Αρχείου Εταιρίας", None))
        self.a_print_report.setText(_translate("MainWindow", "Μισθοδοσία", None))
        self.a_pros.setText(_translate("MainWindow", "Προσλήψεις", None))
        self.a_pros.setStatusTip(_translate("MainWindow", "Διαχείρηση προσλήψεων εργαζομένων", None))
        self.a_apol.setText(_translate("MainWindow", "Απόλυση", None))
        self.a_apox.setText(_translate("MainWindow", "Οικιοθελής αποχώρηση", None))
        self.a_fmyFiscal.setText(_translate("MainWindow", "Οριστική ΦΜΥ", None))
        self.a_apd.setText(_translate("MainWindow", "ΑΠΔ Περιόδου", None))
        self.a_calcmis.setText(_translate("MainWindow", "Μισθοδοσία", None))
        self.a_tables.setText(_translate("MainWindow", "Πίνακες εφαρμογής", None))
        self.a_fpr.setText(_translate("MainWindow", "Στοιχεία εργαζομένων", None))
        self.a_fpr.setStatusTip(_translate("MainWindow", "Στοιχεία εργαζομένων", None))
        self.a_pard.setText(_translate("MainWindow", "Παρουσίες Details", None))
        self.a_exit.setText(_translate("MainWindow", "Έξοδος", None))
        self.a_exit.setStatusTip(_translate("MainWindow", "Έξοδος από την εφαρμογή", None))
        self.a_peri.setText(_translate("MainWindow", "Περί...", None))
        self.a_sql.setText(_translate("MainWindow", "Εξαγωγή σε SQL", None))
        self.a_par.setText(_translate("MainWindow", "Παρουσίες Master", None))
        self.a_xrisi.setText(_translate("MainWindow", "Χρήσεις", None))
        self.a_eid.setText(_translate("MainWindow", "Ειδικότητες", None))
        self.a_ypok.setText(_translate("MainWindow", "Υποκαταστήματα", None))
        self.a_auto_par.setText(_translate("MainWindow", "Αυτόματες παρουσίες", None))
        self.a_pros_wizard.setText(_translate("MainWindow", "Οδηγός Νέας Πρόσληψης", None))
        self.a_print_report_apod.setText(_translate("MainWindow", "Αποδείξεις", None))

import res_rc
