--Δημιουργία πινάκων για εφαρμογή εσόδων-εξόδων / Λογιστικής.
CREATE TABLE IF NOT EXISTS lmo(
id INTEGER PRIMARY KEY,
lmo TEXT NOT NULL UNIQUE,
lmop TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS tr(
id INTEGER PRIMARY KEY,
dat DATE NOT NULL,
par TEXT NOT NULL,
trp TEXT
);
CREATE TABLE IF NOT EXISTS trd(
id INTEGER PRIMARY KEY,
id_tr INTEGER NOT NULL,
id_lmo INTEGER NOT NULL,
xr NUMERIC NOT NULL DEFAULT 0,
pi NUMERIC NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS eet(
hm DATE PRIMARY KEY,
es NUMERIC NOT NULL DEFAULT 0,
ej NUMERIC NOT NULL DEFAULT 0,
vs NUMERIC NOT NULL DEFAULT 0,
vj NUMERIC NOT NULL DEFAULT 0
);
