CREATE TABLE IF NOT EXISTS co(
id INTEGER PRIMARY KEY,
key TEXT NOT NULL UNIQUE,
val TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ptyp(
id INTEGER PRIMARY KEY,
ptyp TEXT NOT NULL UNIQUE,
ptypp TEXT NOT NULL UNIQUE
);

INSERT INTO ptyp VALUES (1, 'ΤΔΑ', 'Τιμολόγιο Δελτίο Αποστολής');

CREATE TABLE IF NOT EXISTS plir(
id INTEGER PRIMARY KEY,
plip TEXT NOT NULL UNIQUE
);

INSERT INTO plir VALUES (1, 'Μετρητά');
INSERT INTO plir VALUES (2, 'Πίστωση');
INSERT INTO plir VALUES (3, 'Πίστωση 30 ημερών');

CREATE TABLE IF NOT EXISTS syn(
id INTEGER PRIMARY KEY,
afm TEXT NOT NULL UNIQUE,
snam TEXT NOT NULL UNIQUE,
ant TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mm(
id INTEGER PRIMARY KEY,
mms TEXT NOT NULL UNIQUE,
mmp TEXT NOT NULL UNIQUE
);

INSERT INTO mm VALUES (1, 'Τεμ', 'Τεμάχιο');
INSERT INTO mm VALUES (2, 'Κιλό', 'Κιλό');
INSERT INTO mm VALUES (3, 'Λίτρο', 'Λίτρο');
INSERT INTO mm VALUES (4, 'Μέτρο', 'Μέτρο');

CREATE TABLE IF NOT EXISTS eid(
id INTEGER PRIMARY KEY,
eidp TEXT NOT NULL UNIQUE,
mm_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS par(
id INTEGER PRIMARY KEY,
dat DATE NOT NULL,
ptyp_id INTEGER NOT NULL,
num TEXT NOT NULL,
plir_id INTEGER NOT NULL,
syn_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS pard(
id INTEGER PRIMARY KEY,
par_id INTEGER NOT NULL,
eid_id INTEGER NOT NULL,
mm_id INTEGER NOT NULL,
pos NUMERIC NOT NULL DEFAULT 0,
tmon NUMERIC NOT NULL DEFAULT 0,
pfpa NUMERIC NOT NULL DEFAULT 0,
ajia NUMERIC NOT NULL DEFAULT 0
);

